import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})


export class HeroService {

  public ListHero: any[] = [
    {
      id:1,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Iron Man",
      tipo:"Marvel",
      poder:"50",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:2,
      nombre:"Batman",
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      tipo:"DC",
      poder:"80",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:3,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Wonder Woman",
      tipo:"DC",
      poder:"90",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:4,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Superman",
      tipo:"DC",
      poder:"100",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:5,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Luke Cage",
      tipo:"Marvel",
      poder:"55",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:6,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"DareDevil",
      tipo:"Marvel",
      poder:"40",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:7,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Booster Gold",
      tipo:"DC",
      poder:"60",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
     {
      id:8,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Spider-Man",
      tipo:"Marvel",
      poder:"100",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:9,
      nombre:"Kyle Rayner (Green Lantern 5)",
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      tipo:"DC",
      poder:"60",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:10,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"The thing",
      tipo:"Marvel",
      poder:"90",
      moral:"Buena",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:11,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Joker",
      tipo:"DC",
      poder:"60",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:12,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Sinister",
      tipo:"Marvel",
      poder:"74",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,

    },
    {
      id:13,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Bullseye",
      tipo:"Marvel",
      poder:"87",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:14,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Cheetah",
      tipo:"DC",
      poder:"80",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
     {
      id:15,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Titanium Man",
      tipo:"Marvel",
      poder:"80",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:16,
      nombre:"Lex Luthor",
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      tipo:"DC",
      poder:"70",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:17,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Sinister",
      tipo:"DC",
      poder:"65",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:18,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Captain boomerang",
      tipo:"DC",
      poder:"20",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:19,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Green Goblin",
      tipo:"Marvel",
      poder:"60",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
    {
      id:20,
      resume:"Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
      nombre:"Red Skull",
      tipo:"Marvel",
      poder:"30",
      moral:"Mala",
      nivelPoder:12,
      favoritos:false,
      team:false,
    },
  ]
  constructor() { }

}


 // La Academia necesita un sistema para administrar héroes y villanos. Los instructores
// deben visualizar personajes, filtrarlos, marcarlos como favoritos, consultar estadísticas
// y organizar equipos.


// id, nombre,
// universo, tipo, poder, nivelPoder y favorito.
